# netlify.toml
[build]
  publish = "./dist"
  command = "rustup toolchain install stable && rustup target add wasm32-unknown-unknown && cargo install trunk --force && trunk build"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
